### ISSUE TITLE
Plan for next sprint 

### ISSUE THREAD

**Issue by Ziadsharkos** [WilliamNazarian/Jobs2Finesse-soen341project2023#1]
By the next sprint, we are planing on finishing the web- development courses assigned to team members that have less experience with the mentioned technologies. In addition, we will be discussing the website front-end design to ensure that it will meet the requirements indicated in the document by understanding how the back-end will be linked to the front-end (i.e how will the database be linked to the website and how the backend functions will retrieve the information from the database). Finally, we will discuss the efficiency of the application by figuring out which data structures or which functions will have less time complexity to use.

**Comment by sanaantoun** [comment]
During the next meeting, we will hopefully close this issue and discuss the about furthers task that will be due for sprint 2!!
